.TH VTSIZE 1
.SH NAME
vtsize \- display and optionally monitor terminal size
.SH SYNOPSIS
.B vtsize
[\fB\-c\fR]
[\fB\-r\fR]
[\fB\-w\fR]
.SH DESCRIPTION
.B vtsize
shows the terminal size
.SH OPTIONS
.TP
.BR \-c
Display only the number of columns
.TP
.BR \-r
Display only the number of rows
.TP
.BR \-w
Continuosly monitor the size of the terminal and output at change
.SH AUTHOR
Fredrik Fornwall <fredrik@fornwall.net>

