.Dd 2015-05-14
.Dt VTSIZE 1
.Sh NAME
.Nm vtsize
.Nd revealer of terminal sizes
.Sh SYNOPSIS
.Nm vtsize
.Bk -words
.Op Fl c
.Op Fl r
.Op Fl w
.Ek
.Sh DESCRIPTION
The
.Nm vtsize
utility shows the terminal size. The default behaviour is to output the number of rows and columns and immediately exit.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Display the number of columns.
.It Fl r
Display the number of rows.
.It Fl w
Continuously watch the terminal for changes.
.El
.Pp
.Sh AUTHOR
.An Fredrik Fornwall Aq Mt fredrik@fornwall.net
